test2以降の再配置で無限ループ

おそらくトライができていない

valueを使っていないのが気がかり